<?php
/**
 * This source file is subject to the agilecodex.com license that is
 * available through the world-wide-web at this URL:
 * https://www.agilecodex.com/license-agreement
 */
?>
<?php
/** @var \Acx\BrandSlider\Block\BrandSlider $block */
$htmlId = $block->getFlexSliderHtmlId();
$brandCollection = $block->getBrandCollection();

?>
<link rel="stylesheet" type="text/css" href="<?php echo $block->getViewFileUrl('Acx_BrandSlider::css/flexslider.css') ?>">

<script type="text/javascript">

    (function () {
        // store the slider in a local variable
        require(['jquery', 'acx/brandslider'], function ($)
        {
            var $window = $(window),
                    flexslider = {vars: {}};
            // tiny helper function to add breakpoints
            function getGridSize() {
                return (window.innerWidth < 577) ? 2 :
                        (window.innerWidth < 992) ? 4 : 5;
            }

            $window.load(function () {
                $('.flexslider').flexslider({
                    animation: "slide",
                    animationLoop: true,
                    pauseOnHover: true,
                    touch: true,
                    itemWidth: 210,
                    slideshow: false,
                    itemMargin: <?= $block->getBrandMargin(); ?>,
                    minItems: getGridSize(), // use function to pull in initial value
                    maxItems: getGridSize(), // use function to pull in initial value
                    <?php
                    if (!$block->getAutoplay()) {
                        echo "slideshow: false, animationLoop: false,";
                    } else {
                        echo 'animation: "slide", slideshow: true, animationLoop: true, slideshowSpeed: ' . $block->getBrandsliderSpeed() . ',';
                    }

                    if (!$block->getDot()) {
                        echo "controlNav: false,";
                    }

                    if (!$block->getNavButton())
                        echo "directionNav: false,";

                    ?>
                });
            });

            // check grid size on resize event
            $window.resize(function () {
                var gridSize = getGridSize();

                flexslider.vars.minItems = gridSize;
                flexslider.vars.maxItems = gridSize;
            });
        });
    }());

</script>

<div class="acx-brandslider-standard">
    <?php
    if ($block->getData("show_title")) {

        ?>
        <div class="acx-content-heading">
            <h2 class="title"><?php echo $block->getTitle(); ?></h2>
        </div>
        <?php
    }

    ?>
    <div class="acx-brandslider-flex-brandslider">
        <div id="<?php echo $htmlId ?>" class="flexslider carousel flexslider-content-image <?php echo $htmlId ?>" style="margin:auto">
            <ul class="slides">
                <?php
                foreach ($brandCollection as $brand) {

                    ?>
                    <li data-thumb="<?php echo $block->getBrandImageUrl($brand) ?>">
                        <img alt="<?php echo $brand->getImageAlt() ?>" 
                             src="<?php echo $block->getBrandImageUrl($brand) ?>"/>
                            <?php if ($brand->getName() && $block->getShowCaption()) { ?>
                            <div class="flex-caption">
                            <?php echo $brand->getName(); ?>
                            </div>
    <?php } ?>
                    </li>

                    <?php
                }

                ?>
            </ul>
        </div>
    </div>
</div>
